SeaCloudsEU/SeaCloudsPlatform

CONTRIBUTING.md

@mbarrientos can you have a look and merge it, if ok?

FIX/DOCS: Update CONTRIBUTING.md

---

dashboard/src/main/java/eu/seaclouds/platform/dashboard/ConfigParameters.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/connectors/DeployerConnector.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/servlets/AddApplicationsServlet.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/servlets/GetAvailableMetricsServlet.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/servlets/GetMatchmakingServlet.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/servlets/GetMetricValueServlet.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/servlets/ListApplicationsServlet.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/servlets/RemoveApplicationsServlet.java

Dashboard was not able to be configured dynamically. Now it expects the following properties to connect to the Deployer engine:
- deployer.host
- deployer.httpPort
- deployer.username
- deployer.password
Also (provisionally, not being used now) supporting properties for the rest of modules:
- planner.endpoint
- monitor.endpoint
- sla.endpoint

FIX(DASHBOARD): Dashboard connection with deployer is now wired through Java properties.

---

dashboard/src/main/java/eu/seaclouds/platform/dashboard/connectors/DeployerConnector.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/servlets/AddApplicationsServlet.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/servlets/GetAvailableMetricsServlet.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/servlets/GetMatchmakingServlet.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/servlets/GetMetricValueServlet.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/servlets/ListApplicationsServlet.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/servlets/RemoveApplicationsServlet.java

Fixes bug where successive requests to servlets were not re-allocating a new connection to the Brooklyn API, hence throwing a exception.

FIX(Dashboard): fixing succesive connections problem.

---

dashboard/src/main/java/eu/seaclouds/platform/dashboard/resources/DeployerResource.java

FIX(Dashboard): Notify the SLA after the rules are installed.

---

planner/core/pom.xml
planner/core/src/main/java/eu/seaclouds/platform/planner/core/OptimizerExample.java
planner/core/src/main/java/eu/seaclouds/platform/planner/core/Planner.java
planner/core/src/main/java/eu/seaclouds/platform/planner/core/WebServiceLayer.java
planner/discoverer/pom.xml
planner/discoverer/src/main/java/eu/seaclouds/platform/planner/discoverer/Discoverer.java
planner/matchmaker/pom.xml
planner/matchmaker/src/main/java/eu/seaclouds/platform/matchmaker/Matchmaker.java
planner/optimizer/pom.xml
planner/pom.xml
pom.xml

uncomment optimizer
enable build for matchmaker and discoverer
fix maven layout for matchmaker,optimizer and discoverer
fix compilation errors (wtf!?)
fix parents in multiple pom.xml
remove unnecessary build plugins as inherited from parents
remove jdk8 requirement

fix planner maven structure

---

common/src/main/java/eu/seaclouds/common/tosca/ToscaSerializer.java
common/src/main/resources/topology-1_0_0_wd03.yml.vm
common/src/test/java/eu/seaclouds/common/tosca/ToscaSerializerTest.java
common/src/test/resources/toscaTestFiles/adp.yml
common/src/test/resources/toscaTestFiles/t.yml

@buccarel, @andreaturli  can you review this?

[FEATURE] TOSCA Serialization Utility

---

usage/installer/src/main/java/eu/seaclouds/modaclouds/dda/MODACloudsDeterministicDataAnalyzer.java
usage/installer/src/main/java/eu/seaclouds/modaclouds/hdb/MODACloudsHistoryDBSshDriver.java
usage/installer/src/main/resources/brooklyn/entity/modaclouds/modacclouds-data-collector.yaml
usage/installer/src/main/resources/brooklyn/entity/modaclouds/modacclouds-data-collector.yaml~

Class MODACloudsHistoryDBSshDriver had some style errors, in particular some tabs for which the maven check-style plugin was complaining. @perezp @andreaturli @rosogon

Solved some problems with the previous PR due to the check-style plugin 

---

discoverer/pom.xml
discoverer/src/main/java/eu/seaclouds/platform/discoverer/core/Discoverer.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/core/Offering.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/core/UniqueFileGen.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/ws/AddOffer.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/ws/CrawlerManager.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/ws/DelOffer.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/ws/FetchOffer.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/ws/SCSpider.java
discoverer/src/main/webapp/WEB-INF/web.xml
discoverer/src/main/webapp/resources/static_addoffer.html
discoverer/src/test/java/eu/seaclouds/platform/discoverer/core/DiscovererTest.java
discoverer/src/test/java/eu/seaclouds/platform/discoverer/core/OfferingTest.java
planner/pom.xml
pom.xml

@andreaturli @szenzaro This is the correct PR for the Discoverer. Can you please review it?
Thanks.

FEATURE (Discoverer): Core and WS layer

---

usage/installer/src/main/java/eu/seaclouds/dashboard/SeacloudsDashboard.java

Fixed bug where dashboard brooklyn entity was downloading the wrong artifact. 
Also setting default values for config keys.

FIX(Dashboard): fixed wrong artifact bug

---

common/src/main/java/eu/seaclouds/common/tosca/ToscaSerializer.java
common/src/test/java/eu/seaclouds/common/tosca/ToscaSerializerTest.java
common/src/test/resources/toscaTestFiles/adp.yml

TOSCA is now readable also from strings.
@perezp can you check this?

FEATURE(common) Serializer: Read TOSCA from string

---

common/pom.xml
dashboard/pom.xml
deployer/pom.xml
discoverer/pom.xml
planner/discoverer/pom.xml
planner/optimizer/pom.xml
planner/pom.xml
pom.xml
sla/sla-core/pom.xml
sla/sla-core/sla-enforcement/pom.xml
sla/sla-core/sla-personalization/pom.xml
sla/sla-core/sla-repository/pom.xml
sla/sla-core/sla-service/pom.xml
sla/sla-core/sla-tools/pom.xml
usage/installer/pom.xml

Pulling up dependencies and also removing some duplicated declarations

Pulling dependencies up to dependencyManagement on parent pom

---

pom.xml
usage/installer/pom.xml
usage/installer/src/main/assembly/files/blueprints/seaclouds-on-byon.yaml
usage/installer/src/main/assembly/files/blueprints/seaclouds.yaml

bump deployer version inside yaml blueprints

Bump brooklyn version to 0.7.0-incubating

---

usage/installer/src/main/assembly/files/blueprints/seaclouds-on-byon.yaml

fix seaclouds-on-byon

---

discoverer/pom.xml
discoverer/src/main/java/eu/seaclouds/platform/discoverer/core/Discoverer.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/core/Offering.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/ws/CloudHarmonySpider.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/ws/CrawlerManager.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/ws/CrawlingResult.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/ws/FetchOffer.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/ws/PaasifySpider.java
discoverer/src/main/java/eu/seaclouds/platform/discoverer/ws/SCSpider.java
discoverer/src/main/webapp/WEB-INF/web.xml

This is the final prototype of the Discoverer. It includes both the PaaSify and the CloudHarmony crawlers. Everything is accessible as RESTful service.
@szenzaro , since you are the one who uses the discoverer most, could you please review it?
Thanks.

feature/DISCOVERER (Final proto)

---

usage/installer/src/main/resources/eu.seaclouds.planner/planner_blueprint.yml

@andreaturli can you review this?

Added blueprint of the Planner for Brooklyn

---

deployer/src/main/java/brooklyn/entity/cloudfoundry/webapp/PaasWebAppCloudFoundryDriver.java

The application tried to bind a non-existent service.

FIX: solving a services management issue.

---

seaclouds-catalog.bom

This PR patches the deployment blueprint for the configuration of the planner  #105.
Since it will be merged soon, after that you can merge also this.
@andreaturli

Planner service configuration patch

---

dashboard/config.yml
dashboard/src/main/java/eu/seaclouds/platform/dashboard/DashboardApplication.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/config/MonitorFactory.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/resources/CoreResource.java
seaclouds-catalog.bom

@MicheleGuerriero  could you review this? This adds also the necessary method to retrieve where Grafana is deployed, so after the installation script become fixed it the dashboard will be wired properly.

Added a Api method to retrieve the location of all the SeaClouds Components

---

seaclouds-catalog.bom

A typo in the catalog was causing the Dashboard to fail while looking for the required Components. @andreaturli could you take a look?

Fixed initialization of the dashboard inside the catalog

---

planner/optimizer/optimizer-service/pom.xml
planner/optimizer/optimizer-service/src/test/resources/log4j.xml

FIX: a change in optimizer-service/pom.xml to be able to find the path of the service during the integration-test process

fix installation of platform from root

---

dashboard/src/main/resources/webapp/projects/add-application-wizard/wizard-step-2.html
dashboard/src/main/resources/webapp/static/js/editor/angular-topology-editor.html
dashboard/src/main/resources/webapp/static/js/editor/editor.js

This removes the ugly button on the dashboard step two. @rosogon  could you take a look?

Cosmetic improvements on the dashboard step 2

---

dashboard/pom.xml
dashboard/src/main/java/eu/seaclouds/platform/dashboard/resources/PlannerResource.java

@andreaturli could you review this?

Removed deprecated Optimizer  dependency from the dashboard.

---

planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/OptimizerInitialDeployment.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLgroupsOptimizerParser.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLmatchmakerToOptimizerParser.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLoptimizerParser.java
planner/optimizer/optimizer-core/src/main/resources/log4j.xml
planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTest.java

The information of cloud resources was not included in the output information of the optimizer, only the names of the cloud resources. 
This PR adds such information to the ADPs created by the optimizer.

increased debug verbosity and adding node templates in optimizer output

---

planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/Optimizer.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/SuitableOptions.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/Anneal.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/MMtoOptModelTransformer.java
planner/optimizer/optimizer-core/src/main/resources/log4j.xml
planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/MMoutputTest.java
planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/MMtoOptModelTransformationTest/MMtoOptModelTransformationTest.java
planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTOSCASeptember2015Test.java
planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTest.java
planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/TestConstants.java
planner/optimizer/optimizer-core/src/test/resources/aam_atos_case_study20Oct.yml
planner/optimizer/optimizer-core/src/test/resources/aam_opttest20Oct.yml
planner/optimizer/optimizer-core/src/test/resources/mmOutputExample20Oct.json
planner/optimizer/optimizer-service/src/test/java/eu/seaclouds/platform/planner/optimizerTest/TestConstants.java
planner/optimizer/optimizer-service/src/test/java/eu/seaclouds/platform/planner/optimizerTest/discovererOutput/DiscovererOutputTest.java
planner/optimizer/optimizer-service/src/test/java/eu/seaclouds/platform/planner/optimizerTest/service/OptimizerServiceOpenShiftTest.java

This PR adds a functionality to the Optimizer to solve the recent issue raised recently regarding a mismatch between its accepted input format and the output format of the Matchmaker. 
Testing has been added and bugs that were found in this period have been corrected. 
17 files have changed, but only 4 of them do not belong to testing.

FEATURE: Optimizer Matchmaker output format with offers. Issue 20 Oct.

---

dashboard/pom.xml
dashboard/src/main/java/eu/seaclouds/platform/dashboard/resources/PlannerResource.java
dashboard/src/main/resources/webapp/app.js
dashboard/src/main/resources/webapp/header/header.html
dashboard/src/main/resources/webapp/index.html
dashboard/src/main/resources/webapp/projects/add-application-wizard/add-application-wizard.html
dashboard/src/main/resources/webapp/projects/add-application-wizard/add-application-wizard.js
dashboard/src/main/resources/webapp/projects/add-application-wizard/wizard-step-1.html
dashboard/src/main/resources/webapp/projects/add-application-wizard/wizard-step-3.html
dashboard/src/main/resources/webapp/projects/add-application-wizard/wizard-step-4.html
dashboard/src/main/resources/webapp/projects/add-application-wizard/wizard-step-5.html
dashboard/src/main/resources/webapp/projects/project/status/status.js
dashboard/src/main/resources/webapp/static/css/app.css
dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/angular-topology-editor.js
dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/topology-editor-utils.js

This PR integrates the planner with the dashboard. Currently there is no  way to test the functionality by using BOM due a problem with the catalog. Please the planner endpoint to http://131.114.3.217:1234 if you want to test it.
@rosogon could you review this?

Wired Dashboard with the Planer for automatic ADP generation. Small fixes.

---

dashboard/src/main/resources/webapp/projects/add-application-wizard/wizard-step-5.html
dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/angular-topology-editor.js
dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/canvas.css
dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/editor-view.html

@rosogon  could you review this?

Fixed Topology Editor/Viewer size

---

dashboard/config.yml
dashboard/src/main/java/eu/seaclouds/platform/dashboard/DashboardApplication.java
seaclouds-catalog.bom

Modified Dashboard Dropwizard configuration in order to use just one port

---

planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/OptimizerInitialDeployment.java
planner/optimizer/optimizer-core/src/test/resources/log4j.xml

Comparison of 4 lines of the information to show with null. 
Short PR and relatively urgent for the rest of developers because some builds may fail in the current status.

FIX: Optimizer Fixing a nullPointerException when showing information for debug

---

dashboard/src/main/resources/webapp/app.js
dashboard/src/main/resources/webapp/projects/project/project.html
dashboard/src/main/resources/webapp/projects/project/project.js

@rosogon  could you review it? Also this could be used as an example to improve topology-status-editor modals.

Replaced bootstrap standard modal with angular based one. Fixes #146

---

dashboard/src/main/java/eu/seaclouds/platform/dashboard/resources/PlannerResource.java
dashboard/src/main/resources/webapp/app.js

Fixes Issue #165. As you raised the issue, @rosogon  could you review it?

Fixed output format mismatch on the Planner service.

---

dashboard/README.md

@andreaturli could you take a look to the Readme.md?

Added SeaClouds Dashboard Readme.md. Part of #164

---

planner/core/pom.xml
planner/core/src/main/java/eu/seaclouds/platform/planner/core/DamGenerator.java
planner/core/src/main/java/eu/seaclouds/platform/planner/core/Planner.java
planner/core/src/test/java/eu/seaclouds/platform/planner/core/DamGeneratorTest.java
planner/core/src/test/resources/generated_adp.yml
planner/matchmaker/src/main/java/eu/seaclouds/planner/matchmaker/constraints/Constraint.java
planner/matchmaker/src/main/java/eu/seaclouds/planner/matchmaker/constraints/ConstraintGreaterOrEqual.java
planner/matchmaker/src/main/java/eu/seaclouds/planner/matchmaker/constraints/ConstraintGreaterThan.java
planner/matchmaker/src/main/java/eu/seaclouds/planner/matchmaker/constraints/ConstraintLessOrEqual.java
planner/matchmaker/src/main/java/eu/seaclouds/planner/matchmaker/constraints/ConstraintLessThan.java
planner/matchmaker/src/main/java/eu/seaclouds/planner/matchmaker/constraints/Version.java
planner/matchmaker/src/test/java/eu/seaclouds/planner/matchmaker/MatchmakerTest.java
planner/matchmaker/src/test/resources/aams/version_aam.yml
planner/matchmaker/src/test/resources/version_offerings.yml
planner/service/plannerconf.yml
planner/service/src/main/java/eu/seaclouds/platform/planner/service/DamGenResource.java
planner/service/src/main/java/eu/seaclouds/platform/planner/service/PlanResource.java
planner/service/src/main/java/eu/seaclouds/platform/planner/service/PlannerApplication.java
planner/service/src/main/java/eu/seaclouds/platform/planner/service/PlannerConfiguration.java
planner/service/src/main/java/eu/seaclouds/platform/planner/service/RePlanResource.java

@rosogon can you review this please?
In order to test it be sure to have a running discoverer and sla-core and provide their urls to the planner configuration.
The PR fixes a bug in the matchmaker, provide an updated version of the dam generator with monitor and sla generators and improves DAM conformance.
@andreaturli: in order to be deployed the bom must be changed. Since you asked me to not update the bom, please contact me if you need help updating it.

(Feature)Planner: core and service update, matchmaker bugfix

---

dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/editor-view.html

Fixes #177 . The number of operations is needed in the optimizer. @adriannieto , @perezp : please, have a look.

FIX(designer): Fixes error setting number of operations in relationship

---

dashboard/.gitignore
dashboard/src/main/resources/webapp/index.html
dashboard/src/main/resources/webapp/projects/add-application-wizard/add-application-wizard.js
dashboard/src/main/resources/webapp/projects/add-application-wizard/wizard-step-3.html
dashboard/src/main/resources/webapp/static/css/app.css
dashboard/src/main/resources/webapp/static/lib/adp-prettifier/adp-prettifier.js

Added user-readable ADP description in the third add-application-wizard

---

planner/core/src/main/java/eu/seaclouds/platform/planner/core/DamGenerator.java
planner/core/src/test/java/eu/seaclouds/platform/planner/core/DamGeneratorTest.java

Avoiding InstancesPOC on final DAM.

Avoiding InstancesPOC on final DAM.

---

planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/Optimizer.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/OptimizerInitialDeployment.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/Reoptimizer.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/Topology.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/TopologyElement.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/AbstractHeuristic.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/Anneal.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/BlindSearch.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/HillClimb.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/ScalingPolicy.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/TOSCAkeywords.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLgroupsOptimizerParser.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLmodulesOptimizerParser.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLoptimizerParser.java
planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTOSCASeptember2015Test.java
planner/optimizer/optimizer-core/src/test/resources/aam_atos_case_study20Oct.yml
planner/optimizer/optimizer-core/src/test/resources/log4j.xml

This PR makes the Optimizer module create repairing policies in the syntax given in Section 7.3 of this document https://docs.google.com/document/d/1Z9RdaWn54IomgI-jCiw-tdutsCdDoHfk67PNUASOFmY/edit# .  
There is also a bit of refactoring of previous repeated code. 
In order to have a finished way to create these policies, for the next PRs it is still required to specify which modules can scale. Following the last directives, I will create the documentation of the module description, usage and run (I do not add it now due to lack of time as somebody may want to see the code for discussion in the next meeting).

FEATURE: Optimizer creates repairing policies in the TOSCA accepted by the Deployer

---

planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/ScalingPolicy.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/TOSCAkeywords.java

This PR addresses a bug on the name of the type of autoscaling policies. 
@kiuby88 Can you take al look?

FIX: naming autoscaling policy type

---

byon/files/seaclouds-catalog.bom
byon/servers.yaml
pom.xml

Updating brooklyn to 0.9.0 SNAPSHOT version

Feature/updating to 0.9.0

---

deployer/pom.xml
deployer/src/main/java/org/apache/brooklyn/entity/openshift/OpenShiftEntity.java
deployer/src/main/java/org/apache/brooklyn/entity/openshift/OpenShiftEntityImpl.java
deployer/src/main/java/org/apache/brooklyn/entity/openshift/PaasEntityDriver.java
deployer/src/main/java/org/apache/brooklyn/entity/openshift/PaasEntityOpenShiftDriver.java
deployer/src/main/java/org/apache/brooklyn/entity/openshift/webapp/OpenShiftWebApp.java
deployer/src/main/java/org/apache/brooklyn/entity/openshift/webapp/OpenShiftWebAppImpl.java
deployer/src/main/java/org/apache/brooklyn/entity/openshift/webapp/PaasWebAppDriver.java
deployer/src/main/java/org/apache/brooklyn/entity/openshift/webapp/PaasWebAppOpenShiftDriver.java
deployer/src/main/java/org/apache/brooklyn/location/openshift/OpenShiftPaasLocation.java
deployer/src/main/java/org/apache/brooklyn/location/openshift/OpenShiftPaasLocationResolver.java
deployer/src/main/resources/META-INF/services/brooklyn.location.LocationResolver
deployer/src/main/resources/META-INF/services/org.apache.brooklyn.api.location.LocationResolver
deployer/src/test/java/eu/seaclouds/location/openshift/AbstractOpenShiftPaasLocationLiveTest.java
deployer/src/test/java/eu/seaclouds/location/openshift/JavaWebOpenShiftLiveTest.java
deployer/src/test/java/eu/seaclouds/location/openshift/OpenShiftYamlTest.java
deployer/src/test/resources/openShift-webapp-db.yaml
pom.xml

Some entities and interfaces are adding which are focus on OpenShift support.
Currently, just Java technology is supported in this provided.
Custom env are supported in this version.
Any OS service owner (add-on) is include for now.
TODO:
* Unifying the code of CF and OS support (for avoiding duplicate code).
* Adding PHP and other technologies support.

FEATURE: Adding OpenShift support.

---

deployer/src/main/java/org/apache/brooklyn/entity/openshift/webapp/PaasWebAppOpenShiftDriver.java
deployer/src/main/resources/META-INF/services/brooklyn.location.LocationResolver
deployer/src/test/java/eu/seaclouds/location/openshift/OpenShiftYamlTest.java
deployer/src/test/resources/openShift-webapp-db.yaml

Removing some useless code
Updating some yamls

Fixing some Openshift issues

---

dashboard/src/main/resources/webapp/index.html
dashboard/src/main/resources/webapp/projects/add-application-wizard/wizard-step-4.html
dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/angular-topology-editor.js
dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/canvas.js
dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/credentials-view.html
dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/credentials.js
dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/types.js

This commit adds a view to enter the credentials. It also contains code to generate a topology from a DAM, and to inject the credentials into a DAM. Thanks to @rosogon for the Credential Editor. This closes #183
Dependencies:
```
<script src="static/lib/angular-topology-editor/graph.js"></script>
<script src="static/lib/angular-topology-editor/canvas.js"></script>
<script src="static/lib/angular-topology-editor/types.js"></script>
<script src="static/lib/angular-topology-editor/forms.js"></script>
<script src="static/lib/angular-topology-editor/editor.js"></script>
<script src="static/lib/angular-topology-editor/status.js"></script>
<script src="static/lib/angular-topology-editor/credentials.js"></script>
<script src="static/lib/angular-topology-editor/angular-topology-editor.js"></script> …
```

FEATURE(designer): Implements a designer view to enter the cloud credentials

---

deployer/src/test/resources/dams/no-artifacs/Noart.jboss-DC-compute-mysql-compute.yaml
deployer/src/test/resources/dams/no-artifacs/Noart.php-compute-mysql-compute.yml
deployer/src/test/resources/dams/no-artifacs/Noart.php-mysql-compute.yml
deployer/src/test/resources/dams/no-artifacs/Noart.tomcat-DC-compute-mysql-compute.yaml
deployer/src/test/resources/dams/no-artifacs/Noart.tomcat-compute-mysql-compute.yaml
deployer/src/test/resources/dams/php-compute.yaml
deployer/src/test/resources/dams/php-mocked.config-database.yaml
deployer/src/test/resources/dams/php-mysql-compute.yml
deployer/src/test/resources/dams/php-mysql.yml
deployer/src/test/resources/dams/php.yaml
deployer/src/test/resources/dams/tomcat-compute-mysql-compute.yaml
deployer/src/test/resources/dams/tomcat-server-DC-compute-mysql-compute.yaml
deployer/src/test/resources/dams/tomcat-server-computed.yaml
deployer/src/test/resources/dams/tomcat.yaml
planner/core/src/test/resources/generatedDAM-php.yml
planner/core/src/test/resources/generated_php_adp.yml

Adding a set of DAMS which were made manually

---

deployer/src/test/resources/dams/dc-standalone.yaml
deployer/src/test/resources/dams/no-artifacs/Noart.jboss-DC-compute-mysql-compute.yaml
deployer/src/test/resources/dams/no-artifacs/Noart.php-DC-compute-mysql-compute.yml
deployer/src/test/resources/dams/no-artifacs/Noart.php-DC-compute.yml
deployer/src/test/resources/dams/no-artifacs/Noart.php-mysql-compute.yml

More Sample DAMs

---

byon/files/seaclouds-catalog.bom

This version improve the location management and it allows to use SameServer and BassicApplications for tosca.nodes.Compute
This new version opens a new issue about the artifacts management, so it should be enhance ASAP

Updating brooklyn-tosca-transformer.

---

planner/README.md

Here a first version of the Planner documentation. @andreaturli can you review it?

Updated documentation for planner

---

planner/core/pom.xml
planner/core/src/main/java/eu/seaclouds/platform/planner/core/Planner.java
planner/core/src/test/java/eu/seaclouds/platform/planner/core/PlannerTest.java
planner/core/src/test/resources/aam_atos_case_study10Dec.yml
planner/core/src/test/resources/adp_atos_case_study10Dec.yml
planner/core/src/test/resources/log4j.xml
planner/core/src/test/resources/offer_all.yaml
planner/service/src/main/java/eu/seaclouds/platform/planner/service/PlanResource.java
planner/service/src/main/java/eu/seaclouds/platform/planner/service/RePlanResource.java

The partial refactor does not change the logic behind the Planner, but it makes the code of `plan()` more clear and intuitive.
I added a test for the `plan()` method that checks the information about deployment in the generated plans.
Could you please check if the ADP used inside the test is valid? (`planner/core/src/test/resources/adp_atos_case_study10Dec.yml`)

FEATURE(Planner) Refactor of plan() method that now takes an AAM as argument. Added a test for the plan() method.

---

deployer/src/test/resources/dams/no-artifacs/Noart.DynamicWeb-compute-mysql-compute.yaml
deployer/src/test/resources/dams/no-artifacs/Noart.DynamicWeb-policies-compute-mysql-compute.yaml

A cluster example and a policy example in DAMs

Using clusters and policies in a DAM

---

dashboard/src/main/java/eu/seaclouds/platform/dashboard/DashboardApplication.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/proxy/DeployerProxy.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/rest/DeployerResource.java
dashboard/src/main/java/eu/seaclouds/platform/dashboard/rest/MonitorResource.java
dashboard/src/test/java/eu/seaclouds/platform/dashboard/proxy/DeployerProxyTest.java
dashboard/src/test/java/eu/seaclouds/platform/dashboard/rest/AbstractResourceTest.java
dashboard/src/test/java/eu/seaclouds/platform/dashboard/rest/DeployerResourceTest.java
dashboard/src/test/java/eu/seaclouds/platform/dashboard/rest/MonitorResourceTest.java
dashboard/src/test/java/eu/seaclouds/platform/dashboard/utils/TestFixtures.java
dashboard/src/test/resources/fixtures/application-tree.json
dashboard/src/test/resources/fixtures/task-summary-delete.json
dashboard/src/test/resources/fixtures/task-summary-deploy.json

This PR fixes some recently discovered bugs on the SeaClouds API. 
- Changes the default DW Jersey client (https://github.com/dropwizard/dropwizard/wiki/Upgrade-guide-0.7.x-to-0.8.x)
- Adds some missing methods to the API.
- Changes some return types.
@perezp Could you take a look?

Fixed some SeaClouds REST API bugs.

---

planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/Translator.java
planner/aamwriter/src/main/resources/examples/nuro_case_study.json
planner/aamwriter/src/main/resources/examples/nuro_case_study_aam.yml
planner/aamwriter/src/test/resources/3tier.json

This also adds nuro aam and topology.

FIX(aamwriter): Avoid exception if threshold value is empty string

---

planner/core/src/resources/mapping/brooklyn-types-mapping.yaml
planner/core/src/test/resources/mapping/brooklyn-types-mapping.yaml

Some NodeTypes modifications.
Artifacts elements are moved to properties.

Improve IaaS types mapping

---

monitor/monitoring-dam-generator-core/src/main/java/eu/seaclouds/monitor/monitoringdamgenerator/dcgenerators/JavaAppDcGenerator.java
monitor/monitoring-dam-generator-core/src/main/java/eu/seaclouds/monitor/monitoringdamgenerator/dcgenerators/MODACloudsDcGenerator.java

This PR solves Issue #228 . @rosogon can you have a look?

Requirements of a DataCollector node template ad now an array.

---

planner/core/src/main/resources/mapping/brooklyn-types-mapping.yaml
planner/core/src/test/resources/mapping/brooklyn-types-mapping.yaml

This is the most important and longest commit

Fix shell  DC's property

---

planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/OptimizerInitialDeployment.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLgroupsOptimizerParser.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLoptimizerParser.java
planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTOSCADecember2015AutoscalingPoliciesTest.java
planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTOSCADecember2015BenchmarkPlatformsTest.java
planner/optimizer/optimizer-core/src/test/resources/aam_nuro_case_study26Jan16.yml

This PR solves the issue #229 . 
- The main contribution is to remove the line of code that changed the node types. Then, it also
- removes the tests that checked whether the node types had changed (this issue had not been accidental, but at some point we had thought that it was the correct solution)
- Adds some log messages
- Adds a file with a test AAM
@adriannieto Since you raised issue #229, could you check this PR?

Solving node template type mismatch

---

planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/Translator.java
planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/modeldesigner/DNode.java
planner/aamwriter/src/test/java/eu/seaclouds/platform/planner/aamwriter/TranslatorTest.java
planner/aamwriter/src/test/resources/translator.json

This PR changes artifacts properties according to the artifact.
Java & war: wars.root
mysql: creationScriptUrl
php & git repo: git.url
php: git.tarball
An example follows:
```
www:
type: sc_req.www
properties:
language: JAVA
artifacts:
- wars.root: http://www.example.com/downloads/www.war
type: tosca.artifacts.File
db_mysql:
type: sc_req.db_mysql
artifacts:
- creationScriptUrl: mysql_script.sql
type: tosca.artifacts.File
php_git:
type: sc_req.php_git
properties:
language: PHP
artifacts:
- git.url: http://www.github.com/SeaCloudsEU/php.git
type: tosca.artifacts.File
php_tarball:
type: sc_req.php_tarball
properties:
language: PHP
artifacts:
- tarball.url: http://www.example.com/downloads/php.zip
type: tosca.artifacts.File
```
@kiuby88 : Could you check this?

FIX(aamwriter): fix some artifacts declarations

---

deployer/src/main/java/org/apache/brooklyn/entity/cloudfoundry/webapp/PaasWebAppCloudFoundryDriver.java

PaaS entities will be running when application will be deployed on the Platform and the main url will be available

Improving isRunning of PaaS entities

---

planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/SuitableOptions.java
planner/optimizer/optimizer-core/src/test/resources/aam_nuro_case_study26Jan16.yml

It was considered useful to have in the Optimizer a default value for the internet latency ( >0 ) in case that such value will not be configured

Add default internet latency

---

byon/files/seaclouds-catalog.bom
deployer/README.md

Updating deployer-brooklyn-tosca artifact

Updating deployer-brooklyn-tosca artifact.

---

planner/optimizer/.gitignore
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/CloudOffer.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/OptimizerInitialDeployment.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/Solution.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/SuitableOptions.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/Topology.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/AbstractHeuristic.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/Anneal.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/BlindSearch.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/HillClimb.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/nfp/QualityAnalyzer.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/TOSCAkeywords.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLmatchmakerToOptimizerParser.java
planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLoptimizerParser.java
planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTOSCADecember2015MultipleInputPointsTest.java
planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/TestConstants.java
planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/nfp/QualityAnalyzerTest.java
planner/optimizer/optimizer-core/src/test/resources/aam_atos_case_studyDisconnected26Feb16.yml
planner/optimizer/optimizer-core/src/test/resources/aam_webChat04Feb16.yml
planner/optimizer/optimizer-core/src/test/resources/log4j.xml
planner/optimizer/optimizer-core/src/test/resources/mmOutputExampleForTestingAtosDisconnectedGraph.json

This PR complements #261 , on the optimizer side. 
The last topologies seen included modules that were not reached by the frontend (admin-interface, simulator). This was not supported by the optimizer, nor the GUI. 
This PR makes the optimizer support this kind of topology, #261 made the GUI support the explicit assignment of frontend. 
An example with a TOSCA topology with a disconnected module is added in this PR, and tests are included using such TOSCA topology

FEATURE: optimizer accepts topologies where not all modules are reached from the frontend

---

monitor/monitoring-dam-generator-core/resources/adp_example.yml
monitor/monitoring-dam-generator-core/src/main/java/eu/seaclouds/monitor/monitoringdamgenerator/adpparsing/YAMLMonitorParser.java
planner/core/src/main/java/eu/seaclouds/platform/planner/core/DamGenerator.java
planner/core/src/test/java/eu/seaclouds/platform/planner/core/DamGeneratorTest.java
planner/service/plannerconf.yml
planner/service/src/main/java/eu/seaclouds/platform/planner/service/DamGenResource.java
planner/service/src/main/java/eu/seaclouds/platform/planner/service/PlannerApplication.java
planner/service/src/main/java/eu/seaclouds/platform/planner/service/PlannerConfiguration.java

This PR moves some Planner information in the configuration file.
There is also a minor issues solved in the monitoring.
@kiuby88, @MicheleGuerriero can you please take a look?

Refactor(Planner) configuration variables

---

planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/modelaam/NodeTemplate.java
planner/aamwriter/src/main/resources/examples/atos_case_study.json
planner/aamwriter/src/main/resources/examples/atos_case_study_aam.yml
planner/aamwriter/src/main/resources/examples/nuro_case_study.json
planner/aamwriter/src/main/resources/examples/nuro_case_study_aam.yml
planner/aamwriter/src/main/resources/examples/web-chat.json
planner/aamwriter/src/main/resources/examples/web-chat_aam.yml
planner/aamwriter/src/test/java/eu/seaclouds/platform/planner/aamwriter/TranslatorTest.java

A relationship is now like:
requirements:
- endpoint:
node: targetNode
type: relationType
properties:
prop.name: connurl
when previously was defined like:
requirements:
- endpoint: targetNode
type: relationType
properties:
prop.name: connurl
This change facilitates the generic handling of relationships in the DAM
generation.

Changes the relationships format to a map inside endpoint element.

---

dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/credentials.js

In new DAM Generator, PaaS providers do not appear as node templates and
the information should be taken from brooklyn policies.
When generating the topology associated to the DAM, the DAM is now
preprocessed to add PaaSes as node templates in the DAM. This only takes
effect for the generation of the topology, and allows the rest of the
code work as it was.

Fixes issue #180: Credentials screen not working after new DAM format

---

discoverer/README.md

This PR add the list of prefetched offerings used in case of troubles with remote resources. It also adds instructions on how to use such list.

Docs(Discoverer) - added offerings file and instructions

---

dashboard/src/main/resources/webapp/wizards/add-application/add-application.js
dashboard/src/main/resources/webapp/wizards/add-application/wizard-step-1.html

The topology is to be pasted inside a textarea. The textarea is
initially hidden, and is shown when a checkbox is checked.

Adds a textarea in step 1 of wizard to specify an initial topology.

---

discoverer/README.md
planner/README.md
planner/core/pom.xml
planner/core/src/main/java/eu/seaclouds/platform/planner/core/application/agreements/AgreementGenerator.java
planner/core/src/main/java/eu/seaclouds/platform/planner/core/application/decorators/SlaInformationDecorator.java
planner/core/src/main/java/eu/seaclouds/platform/planner/core/utils/HttpHelper.java
planner/core/src/test/java/eu/seaclouds/platform/planner/core/DamGeneratorTest.java
planner/service/plannerconf.yml

- Updated Planner configuration file with "cloudfoundry-istance" artifact
- Updated Planner README with all configuration variables
- Updated Discoverer README with mongoimport as requirement
- Fixed DAM Generator issue, now Monitoring rules are correctly passed to SLA 
@rosogon, @jacopogiallo can you please review it?

Docs/Fix(Planner), Docs(Discoverer)

---

dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/editor.css
dashboard/src/main/resources/webapp/wizards/add-application/add-application.js

Previously, the nodes were rounded by a green or red line (not easy to distinguish between them). Now  the background is in light green or red.

Fixes a javascript error and improves nodes look in status screen.

---

dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/canvas.js
dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/credentials.js

The insertion of credentials into DAM in the last step of wizard was not working for PaaS providers. This PR fixes this.

Fixes issue reinserting credentials for PaaS nodes into DAM.

---

byon/files/seaclouds-catalog.bom

Updates the url of the creation script. The new script creates an additional user to connect from localhost.

Fixes type of sla-db and updates the creation script

---

deployer/src/main/java/eu/seaclouds/policy/SeaCloudsMonitoringInitializationPolicies.java
deployer/src/test/java/eu/seaclouds/policy/SeaCloudsMonitoringInitializationPolicyTest.java

Solving a little issue regarding the children of an application that have to be monitoring.

Subchild support
