usage/installer/src/main/java/eu/seaclouds/modaclouds/dda/MODACloudsDeterministicDataAnalizerSshDriver.java, usage/installer/src/main/java/eu/seaclouds/modaclouds/dda/MODACloudsDeterministicDataAnalyzer.java, usage/installer/src/main/java/eu/seaclouds/modaclouds/hdb/MODACloudsHistoryDB.java, usage/installer/src/main/java/eu/seaclouds/modaclouds/hdb/MODACloudsHistoryDBDriver.java, usage/installer/src/main/java/eu/seaclouds/modaclouds/hdb/MODACloudsHistoryDBImpl.java, usage/installer/src/main/java/eu/seaclouds/modaclouds/hdb/MODACloudsHistoryDBSshDriver.java, usage/installer/src/main/java/eu/seaclouds/modaclouds/manager/MODACloudsMonitoringManager.java, usage/installer/src/main/java/eu/seaclouds/modaclouds/manager/MODACloudsMonitoringManagerSshDriver.java, usage/installer/src/main/resources/brooklyn/entity/modaclouds/modaclouds-historydb.yaml, usage/installer/src/main/resources/brooklyn/entity/modaclouds/modaclouds.yaml~, usage/installer/src/test/java/eu/seaclouds/modaclouds/kb/MODACloudsHistoryDBntegrationTest.java
@perezp @andreaturli @rosogon 
MODAClouds Brooklyn entities modified in order to support the the new version of the monitoring, TOWER4 CLouds:
- modified ssh driver and the main class the data analyzer entities to retrieve release 0.2 and be able to launch and configure it with the available parameters
- modified ssh driver and the main class within the monitoring manager entities to retrieve  release 0.2 from tower4clouds repo and be able to launch and configure it with the available parameters
- converted all the knoledge base entities into the history db entities. Now it is possible to retrive release 0.2 of the history dbfrom tower4clouds repo and to launch and configure it with the available parameters
=> Updates in usage/installer to support MODAClouds TOWER4 Clouds

usage/installer/src/main/assembly/files/blueprints/seaclouds-on-byon.yaml, usage/installer/src/main/assembly/files/blueprints/seaclouds.yaml
These lines were missing from the master.  
I'm not sure if they are still valid. F.e., deployer uses $brooklyn:component("monitoring").component("child","manager"), instead of directly component("manager").
=> FIX(usage): Added T4C env vars to sla core

dashboard/src/main/resources/webapp/projects/add-application-wizard/add-application-wizard.html
This will allow to the dashboard to skip the third step to be able to deploy applications with seaclouds if the user already has all the neccessary inputs (Deployment yaml, monitoring rules and sla agreements).
@andreaturli  could you take a look?
=> Workaround to allow the wizard to skip the matchmake/optimization/dam-generation step.

usage/installer/README.md, usage/installer/src/main/assembly/files/blueprints/seaclouds-on-byon.yaml, usage/installer/src/main/assembly/files/blueprints/seaclouds.yaml
- add planner to seaclouds-on-byon.yaml
- remove authN from deployer
- fix seaclouds.yaml blueprint (deployed on AWS EC2)
=> integrate planner yaml

deployer/pom.xml, deployer/src/main/java/org/apache/brooklyn/entity/SourceNameResolver.java, deployer/src/main/java/org/apache/brooklyn/entity/php/PhpWebAppDriver.java, deployer/src/main/java/org/apache/brooklyn/entity/php/PhpWebAppService.java, deployer/src/main/java/org/apache/brooklyn/entity/php/PhpWebAppSoftwareProcess.java, deployer/src/main/java/org/apache/brooklyn/entity/php/PhpWebAppSoftwareProcessImpl.java, deployer/src/main/java/org/apache/brooklyn/entity/php/PhpWebAppSshDriver.java, deployer/src/main/java/org/apache/brooklyn/entity/php/httpd/PhpHttpdDriver.java, deployer/src/main/java/org/apache/brooklyn/entity/php/httpd/PhpHttpdServer.java, deployer/src/main/java/org/apache/brooklyn/entity/php/httpd/PhpHttpdServerImpl.java, deployer/src/main/java/org/apache/brooklyn/entity/php/httpd/PhpHttpdSshDriver.java, deployer/src/test/java/eu/seaclouds/apache/PhpHttpdServerIntegrationTest.java, deployer/src/test/java/eu/seaclouds/apache/PhpYamlTest.java, deployer/src/test/resources/php-helloworld.yaml
Updated support for PHP applications on Brooklyn. This is based on the initial work done by @kiuby88 on the fork of incubator-brooklyn at SeaCloudsEU.
Apache2 is being configurated by default on machines where the apps are deployed. Apps can be deployed either by providing a tarball or a valid git repository.
=> Added Brooklyn entities for PHP applications.

deployer/src/test/resources/tosca-templates/tomcat-hosted.yaml
A first TOSCA topology supported on brooklyn-tosca project.
=> Simple TOSCA topology for deploying a TomcatServer on aws

dashboard/src/main/resources/webapp/static/js/editor/canvas.js, dashboard/src/main/resources/webapp/static/js/editor/editor.js, dashboard/src/main/resources/webapp/static/js/editor/forms.js, dashboard/src/main/resources/webapp/static/js/editor/status.js
When clicking a node or link in the design-topology step, it behaved as on the Status screen. This PR fixes the bug. The code delegates popovertitle and popovercontent functions to a delegate object, instead of overriding the default functions in the hierarchy.
@adriannieto, could you take a look?
=> FIX(Designer): Fixed node tooltip when designing topology

planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/Translator.java, planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/modelaam/NodeTemplate.java, planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/modeldesigner/DNode.java, planner/aamwriter/src/test/java/eu/seaclouds/platform/planner/aamwriter/TranslatorTest.java, planner/aamwriter/src/test/resources/3tier.json
All the properties defined in a designer node that are explicitly handled in the translation process are stored in the properties of the node template.
There are two exceptions:
* The language of a module is implicitly stored in the node_type, just for the matchmaking process. With this PR, the language is also a property of the node template, so each process that needs to know  the languages of the components, is able to retrieve it (e.g. monitoring rules generator)
* The QoS section of each component are not stored in the node_template properties.
=> FEATURE(aamwriter): Language and not handled properties are stored in node template props

dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/editor-view.html, dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/editor.js
If the user selects IaaS or PaaS for a module, the matchmaker is not passing any suitable offering to the optimizer. This PR fixes this ( #167 )
@adriannieto : Could you review this?
=> FIX(dashboard): Fixes #167: AAM uses node type equals IAAS or equals PAAS

dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/editor-view.html, dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/editor.js, dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/forms.js, planner/aamwriter/src/test/java/eu/seaclouds/platform/planner/aamwriter/TranslatorTest.java, planner/aamwriter/src/test/resources/3tier.json
Add a property to specify if a module is allowed to be autoscaled or not.
A generated AAM containing this property is:
```
tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: atos
imports:
- tosca-normative-types:1.0.0.wd03-SNAPSHOT
topology_template:
node_templates:
www:
type: sc_req.www
properties:
autoscale: '1'
requirements:
- endpoint: db
db:
type: sc_req.db
properties:
autoscale: '0'
mysql_version:
constraints: []
node_types:
sc_req.www:
derived_from: seaclouds.nodes.SoftwareComponent
sc_req.db:
derived_from: seaclouds.nodes.database.mysql.MySqlNode
properties:
mysql_support:
constraints:
- equal: true
mysql_version:
constraints: []
groups:
operation_www:
members:
- www
policies:
- dependencies:
operation_db: ''
- QoSRequirements:
response_time:
less_than: 200.0 ms …
```
=> FEATURE(dashboard): Autoscale property in module properties

planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/OptimizerInitialDeployment.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/TopologyElement.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/ComputeType.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/ScalingPolicy.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/TOSCAkeywords.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLmodulesOptimizerParser.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLoptimizerParser.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLtypesOptimizerParser.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/AbstractTest.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerComputeTypeTest.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTOSCADecember2015AutoscalingPoliciesTest.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTOSCASeptember2015Test.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTOSCAjuly2015Test.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTest.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/TestConstants.java, planner/optimizer/optimizer-core/src/test/resources/aam_atos_case_study10Dec.yml, planner/optimizer/optimizer-core/src/test/resources/log4j.xml
In the current state there are modules with which there are autoscaling policies associated. However such modules do not belong to scalable types.
This PR addresses it, by changing the type of the modules that have associated autoscaling policies to seaclouds.nodes.ControlledDynamicWebAppCluster.
This PR also creates seaclouds.nodes.Compute type in node_types. 
Tests have been created to check that changes in the types have been produced in the correct nodes.
You can see that I've not squashed the commits. I've done it on purpose. I would like @rosogon looking at the two firsts because they are related to his PR that is currently failing. I thought it would be clearer for him if I do not squash all the changes into one already from the beginning.
=> Change types scalable nodes

byon/files/seaclouds-catalog.bom
Adding first brooklyn TOSCA support to SeaClouds Deployer.
Next step would be to use maven instead of a fixed jar.
=> Adding first brooklyn-tosca support.

monitor/README.md
This PR adds just a minor update to the monitor module documentation related to how to configure the monitor after the deployment. In particular this fix is required in order to enable the monitoring of the response time at the level of the application module, since by default Tower 4Clouds allow just to monitor the response time of single services/operations. @andreaturli can you have a look at this?
=> Monitor documentation updated.

README.md, byon/files/seaclouds-catalog.bom, byon/servers.yaml, dashboard/README.md, dashboard/config.yml, dashboard/src/main/java/eu/seaclouds/platform/dashboard/DashboardApplication.java, dashboard/src/main/java/eu/seaclouds/platform/dashboard/DashboardConfiguration.java, dashboard/src/main/java/eu/seaclouds/platform/dashboard/DashboardHealthCheck.java, dashboard/src/main/java/eu/seaclouds/platform/dashboard/proxy/GrafanaProxy.java, dashboard/src/main/java/eu/seaclouds/platform/dashboard/rest/CoreResource.java, dashboard/src/test/java/eu/seaclouds/platform/dashboard/rest/AbstractResourceTest.java
With this PR InfluxDB and Grafana is installed when SeaClouds is deployed. This will ease the testing of an integrated workflow. Maybe the Monitor documentation should be updated to match the new setup with for example what the new config keys means (the Dashboard readme.md is updated properly) @MicheleGuerriero   WTDY?.
This PR is related with #206 and fixes #180
=> Added InfluxDB + Grafana to the SeaClouds catalog

monitor/monitoring-dam-generator-core/resources/adp_example.yml, monitor/monitoring-dam-generator-core/src/main/java/eu/seaclouds/monitor/monitoringdamgenerator/adpparsing/YAMLMonitorParser.java, monitor/monitoring-dam-generator-core/src/test/java/eu/seaclouds/monitor/monitoringdamgenerator/MonitoringGenerationTest.java, monitor/monitoring-dam-generator-core/src/test/java/eu/seaclouds/monitor/monitoringdamgenerator/adpparsing/AdpParsingTest.java, planner/core/src/test/resources/generated_adp.yml
This PR fixes an issue in the monitor-dam-generator related to node templates in the ADP of type seaclouds.node.Compute or seaclouds.node.Platform that was previously defined to be seaclouds.Node.Compute, sea clouds.Node.Platform. The fix is applied also in the resources used by the planner for its tests.
@PaoloCifariello can you have a look at this?
=> Fixed wrong ADP nodes prefixes in the monitoring-dam-generator.

dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/credentials-view.html, dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/credentials.js, dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/types.js
This PR adds forms to enter the credentials for amazon, openshift and cloudfoundry. Another generic form (to simply type key/values separated by ';') is implemented in case the provider is not recognized. The credentials are stored in the brooklyn_location policy according the properties defined in section 7.2.2 of DAM model
It is important that the location property of the node_template related to the provider matches the variable ```form_by_provider``` (credential.js:23). I would need @kiuby88 and @jacopogiallo to check this.
@adriannieto : Could you check the PR? Thanks
=> FEATURE(credentials): Add credentials forms and credentials storage according to provider.

planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/Translator.java, planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/modeldesigner/DGraph.java, planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/modeldesigner/DLink.java, planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/modeldesigner/DNode.java, planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/modeldesigner/DRequirements.java, planner/aamwriter/src/test/java/eu/seaclouds/platform/planner/aamwriter/DesignerModelTest.java, planner/aamwriter/src/test/resources/frontend.json, planner/aamwriter/src/test/resources/wrong_frontend.json
This PR allows the specification of a frontend module in application_requirements/frontend element. Before this, the frontend module is calculated as the source node of the flow graph.
If the frontend (the node "visible" to the users, to which we want to apply the QoS requirements) is not the source of the node graph (assume a test module that connects to the frontend), the frontend must be specified.
Example:
```
{
"nodes": [ ... ],
"links": [ ... ],
"application_requirements": {
"response_time": "2000",
"availability": 0.98,
"cost": "200",
"workload": "50",
"frontend": "www"
}
}
```
=> FEATURE(aamwriter): Handles property application_requirements/frontend

dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/credentials-view.html, dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/credentials.js
This PR handles the prefix `tosca.nodes.(Compute|Platform)` as the new prefix for cloud types. This change in the planner is still not on master, so this PR still handles `seaclouds.nodes.(Compute|Platform)` as valid prefixes.
=> FIX(credentials): add support of new cloud type prefixes

dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/editor-view.html, dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/editor.js, planner/aamwriter/src/test/java/eu/seaclouds/platform/planner/aamwriter/TranslatorTest.java, planner/aamwriter/src/test/resources/translator.json
This PR adds db_name, db_user and db_password properties in the AAM for the database nodes. It also adds the fields needed in the UI to collect this data.
The following json topology
```
{
"name": "example",
"nodes": [{
"name": "db1",
"label": "db1",
"type": "Database",
"properties": {
"category": "database.mysql.MySqlNode",
"autoscale": true,
"artifact": "",
"min_version": "5",
"max_version": "5",
"db_name": "$DB_NAME",
"db_user": "$DB_USER",
"db_password": "$DB_PWD",
"qos": [],
"benchmark_rt": "",
"benchmark_platform": ""
},
}],
"links": [],
"application_requirements": {
"response_time": "2000",
"availability": 0.98,
"cost": "200",
"workload": "50"
}
}
```
generates the following AAM:
```
tosca_definitions_version: tosca_simple_yaml_1_0_0_wd03
description: example
imports:
- …
```
=> FEATURE: AAM contains db_name, db_user, db_password properties

sla/sla-core/sla-personalization/pom.xml
sla-personalization depends on tower4clouds:rules, which 
depends on log4j-over-slf4j. This leads to an exception at runtime
described in http://www.slf4j.org/codes.html#log4jDelegationLoop
This commits adds the exclusions needed to work around the problem. Although it is not affecting the SLA in SeaClouds (I don't know why), it has affected in other contexts, and therefore may affect SeaClouds SLA in the future.
The exclusions may be added to the parent pom instead of sla-personalization, but I would need agreement from the other modules. 
@andreaturli , @kiuby88 , @adriannieto , @MicheleGuerriero : WDYT?
=> Avoids log4j-over-slf4j recursion

byon/files/seaclouds-catalog.bom, deployer/src/main/resources/brooklyn/brooklyn-tosca-config.yaml
This allows DAM to avoid NodeTypes definitions
=> Adding SeaClouds types to TOSCA engine.

planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/OptimizerInitialDeployment.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/Solution.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/AbstractHeuristic.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/Anneal.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/BlindSearch.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/HillClimb.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/SearchMethod.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/nfp/QualityAnalyzer.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLoptimizerParser.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/AbstractTest.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTOSCADecember2015UniqueSolutionsTest.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/TestConstants.java, planner/optimizer/optimizer-core/src/test/resources/aam_nuro_case_study26Jan16.yml, planner/optimizer/optimizer-core/src/test/resources/aam_singleModule11Feb16.yml, planner/optimizer/optimizer-core/src/test/resources/mmOutputExample20OctSingleOffer.json
This PR avoids returning replicated ADPs in case that there exist just a very few cloud combinations. 
It is intended to solve issue #240 
It includes tests for the AAM that raised the issue; an AAM with only one module and just one cloud offer as possibility.
=> Remove duplicate ADPs. Solving issue #240

dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/editor-view.html, dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/editor.js, planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/Translator.java, planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/modelaam/NodeTemplate.java, planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/modeldesigner/DLink.java, planner/aamwriter/src/test/java/eu/seaclouds/platform/planner/aamwriter/TranslatorTest.java, planner/aamwriter/src/test/resources/translator.json
The link form in the designer asks for the env var.
The env var is introduced in the AAM at aamwriter time.
This also removes a previous feature where credentials were stored in a
file.
For example, the following topology:
```
[...]
"links": [
{
"source": "www",
"target": "webservices",
"properties": {
"calls": "2",
"operation_type": "seaclouds.relation.connection.endpoint.host",
"env_var": "connurl"
}
},
[...]
```
generates the following requirement in the node template:
```
www:
type: sc_req.www
properties:
language: JAVA
location: DYNAMIC
location_option: FOLLOW_SUN
autoscale: true
artifacts:
- wars.root: http://www.example.com/downloads/www.war
type: tosca.artifacts.File
requirements:
- endpoint: webservices
type: seaclouds.relation.connection.endpoint.host
properties:
prop.name: …
```
=> Adds the env var where an endpoint url is stored.

planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/OptimizerInitialDeployment.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/Solution.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/Anneal.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/HillClimb.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/nfp/QualityAnalyzer.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/nfp/QualityInformation.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/ScalingPolicy.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/TOSCAkeywords.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTOSCADecember2015AutoscalingPoliciesTest.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/nfp/QualityAnalyzerTest.java
Changed the optimizer code to create policies with the structure as in the following example: 
```
policies:
- autoscaling:
type: seaclouds.policies.autoscaling.AutoScalerPolicy
metric: seaclouds.metrics.requestPerNode
autoscaler.resizeDownStabilizationDelay: 120000
metricLowerBound: N1
metricUpperBound: N2
minPoolSize: N3
maxPoolSize: N4
```
=> FIX: create autoscaler policy with agnostic information

planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/CloudOffer.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/OptimizerInitialDeployment.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/Topology.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/TopologyElement.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/heuristics/HillClimb.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/nfp/QualityAnalyzer.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/nfp/QualityInformation.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/TOSCAkeywords.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLgroupsOptimizerParser.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLmodulesOptimizerParser.java, planner/optimizer/optimizer-core/src/main/java/eu/seaclouds/platform/planner/optimizer/util/YAMLoptimizerParser.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/AbstractTest.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/OptimizerTOSCADecember2015NoQoSinfoInAAMTest.java, planner/optimizer/optimizer-core/src/test/java/eu/seaclouds/platform/planner/optimizerTest/TestConstants.java, planner/optimizer/optimizer-core/src/test/resources/aam_atos_case_studyNoQoSInfoNoAutoscale26Feb16.yml
With this PR the optimizer reads the `autoscale` value from AAM even if the AAM does not contain  `QoSinfo` . Tests for this case have been added. 
Before this PR, when it was found the lack of the required quality information `QoSinfo` the `autoscale` value was not read but it took the default value of `true`
=> Scaling policies optimizer

dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/editor-forms.js, planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/Translator.java, planner/aamwriter/src/main/java/eu/seaclouds/platform/planner/aamwriter/modeldesigner/DNode.java, planner/aamwriter/src/test/java/eu/seaclouds/platform/planner/aamwriter/TranslatorTest.java, planner/aamwriter/src/test/resources/translator.json
The location was not properly handled in the AAMWriter.
Now, the format in the AAM is (e.g.):
```
sc_req.www:
derived_from: seaclouds.nodes.php.httpd.PhpHttpdServer
properties:
resource_type:
constraints:
- equal: compute
continent:
constraints:
- equal: Europe
```
This also changes the continent values to the right ones expected by the
matchmaker.
=> Fixes #275: Location not considered in matchmaker

dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/angular-topology-editor.js, dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/editor.css, dashboard/src/main/resources/webapp/static/lib/angular-topology-editor/topology-editor-utils.js
Status.fromjson recreates() the whole topology structure. This commit
calls Status.fromjson only when the application changes.
TODO: the new code may update other properties than status (e.g., module
urls).
=> Fixes jumping topology on status screen.

sla/sla-core/sla-repository/src/main/resources/sql/01database.sql
Adds atossla user to connect from localhost.
From: https://dev.mysql.com/doc/refman/5.5/en/problems-connecting.html
If you cannot figure out why you get Access denied, remove from the user table all rows that have Host values containing wildcards (rows that contain '%' or '_' characters). A very common error is to insert a new row with Host='%' and User='some_user', thinking that this enables you to specify localhost to connect from the same machine. The reason that this does not work is that the default privileges include a row with Host='localhost' and User=''. Because that row has a Host value 'localhost' that is more specific than '%', it is used in preference to the new row when connecting from localhost! The correct procedure is to insert a second row with Host='localhost' and …
=> Ensures sla-service is able to connect to db from localhost

dashboard/src/main/java/eu/seaclouds/platform/dashboard/proxy/SlaProxy.java, dashboard/src/main/java/eu/seaclouds/platform/dashboard/rest/SlaResource.java, dashboard/src/main/resources/webapp/app.js, dashboard/src/main/resources/webapp/applications/application/sla/sla.html, dashboard/src/main/resources/webapp/applications/application/sla/sla.js, dashboard/src/test/java/eu/seaclouds/platform/dashboard/proxy/SlaProxyTest.java, dashboard/src/test/java/eu/seaclouds/platform/dashboard/rest/AbstractResourceTest.java, dashboard/src/test/java/eu/seaclouds/platform/dashboard/rest/SlaResourceTest.java, dashboard/src/test/java/eu/seaclouds/platform/dashboard/utils/TestFixtures.java, dashboard/src/test/resources/fixtures/penalties.json
A new REST endpoint is added to retrieve the penalties associated to an
(agreement, term) pair.
The web application adds a new table in SLA tab that displays the
penalties for a term (under violations table).
=> Adds penalties API and display of penalties in dashboard
